module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1440px',
    },
    colors: {
      'black': '#292F33',
      'white': '#FFFFFF',
      'grayEC': '#ECECEC',
      'grayFC': '#FCFCFC',
      'grayE8': '#e8e8e8',
      'gray1': '#8B8B8B',
      'gray2': '#505050',
      'blue1': '#CCD4DA',
      'blue2': '#F4F8FB',
      'blue3': '#E0FFF9',
      'blue4': '#D4EFFF',
      'blue5': '#007EC5',
      'blue6': '#00C09E',
      'blue7': '#088178',
      'greenBorder': '#24FF00',
      'greenText': '#0FB900',
      'transparent': 'transparent',
      'bgProfile': '#F5F5F5',
      'red': '#FF0000',
    },
  },
  plugins: [],
} 