name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # chỉ áp dụng khi push code lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Chọn phiên bản Node.js mà bạn muốn cài đặt

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t duchaidev/fe-shopweb:latest .

    - name: Push Docker Image
      run: docker push duchaidev/fe-shopweb:latest
